export const FETCHED_USER = 'FETCHED_USER'

export const TESTING_REDUCER = 'TESTING_REDUCER'

export const LOADING_USER = 'LOADING_USER'

export const ADD_REMINDER = 'ADD_REMINDER'

export const ADD_CONTACT = 'ADD_CONTACT'

export const UPDATE_REMINDER = 'UPDATE_REMINDER'

export const DELETE_REMINDER = 'DELETE_REMINDER'